---
title: "Stats 506 (Fall 2020) Final Project"
author: "Suppapat Korsurat, skorsu@umich.edu"
date: "`r format.Date(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    df_print: paged
    theme: readable
    toc: yes
    toc_float: true
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(knitr)
library(foreign)
library(png)
library(linguisticsdown) ## Import Picture form GitHub site.
```

## Introduction
There is much medical research claimed that diabetes and hypertension are 
associate with each other. Moreover, some of the studies said that diabetes is
the main factor for developing hypertension. The author curious whether this 
claim is valid for US citizens or not. Hence, this analysis's primary question 
is that "For the US people, Does diabetes affect the prevalence of 
hypertension?" In addition, the author wants to know whether this claim holds 
for each level of the aspects or not. Three aspects arouse the author's 
interests are gender, age, and obesity. (91 words)

The method used in this analysis is the Odd Ratios, retrieving from the 
logistic regression. The author decided to create two models for this 
analysis; both of them used hypertension status as a response variable.
(31 words)

## Data
The data used in this analysis is provided by the National Health and Nutrition Examination Survey (NHANES). The author decides to use the data between the 
year 2011 to 2018. (30 words)

According to the data, some respondents were collected the blood pressure data 
more than once. The author decided to use the latest record for each 
respondent. After filtering out the respondent who does not have the blood 
pressure data and the error in the data, the records with systolic less than 60
mmHG and/or diastolic should higher than 40 mmHG, the author classified the 
data into two groups by using the criteria provided in this 
[link](https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings): normal and hypertension. (77 words)

Apart from the blood pressure, the author will use only the respondent whose 
age is not less than 18 years old at least 18 years old as both hypertension 
and diabetes might not be detected precisely in children. Furthermore, the 
author divided the citizen into three groups: adults, middle-aged, 
and seniors. (51 words)

For the obesity status, the Body Mass Index was used to cluster the respondent
into two groups. The one who has BMI not less than 30 was considered obese; 
otherwise, he was considered no obese. (30 words)

## Method

Data / Methods: Describe your data source and the methods you used. There should be enough detail here that I could repeat your analysis. Focus on what you did, not how you did it.

Include a sentence with a link to a GitHub repository containing your code.

## Result

## Conclusion

## Discussion

Results: What did you find? This should be the largest section and is where all of your tabular/graphical elements go.
Conclusion / Discussion: What do your results allow us to conclude about the question you posed? What are the strengths and limitations of your analysis?

